# Generated by Django 5.2.7 on 2025-10-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Şifre'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='surname',
            field=models.CharField(max_length=255, verbose_name='Soyad'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
    ]
